#name: braccio

defaults: #all defaults can be overwritten per node
  eds_pkg: motor_control_own
  eds_file: "config/eds/ASDA_A2_1042sub980_C_ORIG_mod_bonSchunkv1.eds" 
  encoder_resolution: 1048576
    
  # the below part of the defaults section is optional
    # canopen_chain_node settings ..
  motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
  motor_layer: #settings passed to motor layer (plugin-specific)
    switching_state: 5 # (Operation_Enable), state for mode switching
  pos_to_device: "rint(rad2deg(pos)*1048576*480/360)" # rad -> mdeg * resolution of encoder * reduction ratio / 360 degree
  pos_from_device: "deg2rad(obj6064)*360/480/1048576" # actual position [count] -> rad
  vel_to_device: "rint(rad2deg(vel)*1048576*480/360*10)" # rad/s -> mdeg/s
  vel_from_device: "deg2rad(obj606C)*360/10/480/1048576" # actual velocity [0.1count/s] -> rad/s
  eff_to_device: "rint(eff)" # just round to integer
  eff_from_device: "0" # unset!! effort on motor!
  
#  dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
#    "6081": "0x90000" # velocity that the trajectory generator attempts to achieve when in position profile mode.
#    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
#    "1017": "1000" # heartbeat producer, set the node to repoduce heart beat signal every second
    
nodes:
  - name: joint_1
    id: 1
    pos_to_device: "rint(rad2deg(pos)*1048576*457/360)" # rad -> mdeg * resolution of encoder * reduction ratio / 360 degree
    pos_from_device: "deg2rad(obj6064)*360/457/1048576" # actual position [count] -> rad
    vel_to_device: "rint(rad2deg(vel)*1048576*457/360)" # rad/s -> mdeg/s
    vel_from_device: "deg2rad(obj606C)*360/457/1048576" # actual velocity [count/s] -> rad/s
    eff_to_device: "rint(eff)" # just round to integer
    eff_from_device: "0" # unset!! effort on motor!
#    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
#    #publish: ["6064!"]  #actual position_actual_value
    encoder_resolution: 1048576
