## joint_names
joint_names: [joint_1]

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## position controller
#joint_group_position_controller:
#  type: position_controllers/JointGroupPositionController
#  joints:
#     - joint_1
#  required_drive_mode: 1

joint_1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint_1
  required_drive_mode: 1

## velocity controller
#joint_group_velocity_controller:
#  type: velocity_controllers/JointGroupVelocityController
#  joints:
#     - joint_1
#  required_drive_mode: 3

#joint_1_velocity_controller:
#  type: velocity_controllers/JointVelocityController
#  joint: joint_1
#  required_drive_mode: 3
